baseURL = "https://arjunkakkalasseri.com/"
languageCode = "en-us"
title = "Arjun Kakkalasseri"

[params]
    author= "Arjun Kakkalasseri"
    description = "Arjun is a web-designer and developer based in Malappuram, KL, India." 
